# We set the language to c because python isn't supported on the MacOS X nodes
# on Travis. However, the language ends up being irrelevant anyway, since we
# install Python ourselves using conda.
language: c

os:
    - linux

# Use Travis' container-based architecture
sudo: false

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - TOX_CMD='tox --'
        - TOX_ARGS='--remote-data'
        # This is the Python version that will be used by the parent conda
        # environment, but it will not be used in the test environments
        # themselves.
        - PYTHON_VERSION=3.6

    matrix:
        # Make sure that installation does not fail
        - TOXENV='py36-stable' TOX_CMD='tox --notest' TOX_ARGS=''
        # Make sure README will display properly on pypi
        - TOXENV='checkdocs'

matrix:
    fast_finish: true
    include:

        # Do a coverage test
        #- env: TOXENV='coverage' TOX_ARGS=''

        # Perform a sanity check of packaging using twine
        - env: TOXENV='twine' TOX_ARGS=''

        # Check for sphinx doc build warnings - we do this first because it
        # may run for a long time
        #- env: TOXENV='docbuild' TOX_ARGS=''

        # Do a code style check
        - env: TOXENV='style' TOX_ARGS=''

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda.sh
    - conda install openssl
    - pip install tox tox-conda

script:
   - $TOX_CMD $TOX_ARGS
